language: java
sudo: required
addons: 
 sonarcloud:
    organization: "oxygenxml-github"
    token: "${SONAR_CLOUD_TOKEN}"
dist: trusty
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - chmod +x travis/checkForTag.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${DITA_TRANSLATION_BUILDER}:@github.com" > .git/credentials
  - ./travis/checkForTag.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - mvn clean install
  - chmod +x travis/install-openjdk11.sh
  - ./travis/install-openjdk11.sh --emit-java-home
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${DITA_TRANSLATION_BUILDER}
  file:
    - target/translation-package-builder-${TRAVIS_TAG}-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
